name: SUMO CI

on:
  schedule:
    - cron:  '30 8 * * 6'

jobs:
   call-sumo-check-workflow:
    if: github.repository == 'ontologyportal/sumo'
    uses: .github/workflows/sumo-ci.yml
    with:
      vampire_timeout: 10800