name: SUMO CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
   call-sumo-check-workflow:
    uses: ./.github/workflows/sumo-ci.yml
    with:
      vampire_timeout: 900
