name: SUMO CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DEFAULT_DOCKER_ACCOUNT: apease

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      image_account: ${{ steps.step1.outputs.image_account }}
    steps:
      - id: step1
        env:
          DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}
        run: echo "image_account=${DOCKER_ACCOUNT:-$DEFAULT_DOCKER_ACCOUNT}" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: job1
    container:
      image: ${{ needs.job1.outputs.image_account }}

    steps:
    - uses: actions/checkout@v3
      with:
        path: sumo

    - name: Setup SigmaKEE
      env:
        SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
        ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
      run: |
        echo "SIGMA_HOME: $SIGMA_HOME"
        mkdir -p $SIGMA_HOME/KBs/WordNetMappings
        wget https://raw.githubusercontent.com/ontologyportal/sigmakee/master/config.xml
        cp ./config.xml $SIGMA_HOME/KBs
        cp -R $ONTOLOGYPORTAL_GIT/sumo/* $SIGMA_HOME/KBs
        cp /opt/WordNet-3.0/dict/* $SIGMA_HOME/KBs/WordNetMappings/
        sed -i "s|/home/theuser/.sigmakee|$SIGMA_HOME|g" $SIGMA_HOME/KBs/config.xml
        sed -i "s|/home/theuser/workspace/sumo|$ONTOLOGYPORTAL_GIT/sumo|g" $SIGMA_HOME/KBs/config.xml
        sed -i "s|/home/theuser/E/bin/e_ltb_runner|/usr/local/bin/e_ltb_runner|g" $SIGMA_HOME/KBs/config.xml
        sed -i "s|/home/theuser/workspace/vampire/vampire|/usr/local/bin/vampire|g" ./sigmakee/config.xml

    - name: Produce SUMO.tptp
      run: java -Xmx8g -classpath "/root/sigmakee/*" com.articulate.sigma.trans.SUMOKBtoTPTPKB

    - name: Run vampire against SUMO.tptp
      run: |
        ls -l /root/sigmakee-runtime/KBs/SUMO.tptp
        /usr/local/bin/vampire --proof tptp -t 900 /root/sigmakee-runtime/KBs/SUMO.tptp > vamp-out.txt || echo "Ignoring vampire exit code"

    - name: Check results
      if: success() || failure()
      run: |
        ls -l /root/sigmakee-runtime/KBs/SUMO.tptp
        ls -l vamp-out.txt
        grep "Refutation found" vamp-out.txt  || echo "Ignoring grep exit code"
        echo "vamp-out.txt"
        cat vamp-out.txt
